### PR TITLE
Update

### PR DESCRIPTION
**Pull request by polgreen**
- updates to latest uclid
- updates syntax of control example to use new float syntax
- updates delphi binary to allow interactive mode for synthesis (control can now be run with uclid test-control.ucl -y "delphi --symo"

### CODE REVIEW

**Comment by saseshia** [comment]
This updated version, unlike the previous one, has a whole copy of uclid sources in the repository. Is that intended or required?

**Comment by polgreen** [comment]
Oh, it was intended but only because i thought the previous version had the source code in as well. Will delete

**Comment by saseshia** [comment]
Corrected a few typos in the Cliff Walking script. I'm getting errors with delphi, otherwise this looks fine. For example, on the CliffWalking script, it outputs this for the run using delphi:

Running uclid on cliff walking.ucl to synthesis agent using delphi
uclid -y "delphi --symo" cliff_walking.ucl
Command unroll is deprecated. Please use bmc, or bmc_noLTL in future for non-LTL properties
Command unroll is deprecated. Please use bmc, or bmc_noLTL in future for non-LTL properties
Successfully instantiated 1 module(s).
Exception in thread "main" java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at uclid.InteractiveProcess.writeInput(InteractiveProcess.scala:81)
        at uclid.smt.SMTLIB2Interface.writeCommand(SMTLIB2Interface.scala:457)
        at uclid.smt.SynthLibInterface.checkSynth(SynthLibInterface.scala:207)
        at uclid.SymbolicSimulator.check(SymbolicSimulator.scala:181)
        at uclid.SymbolicSimulator.$anonfun$execute$6(SymbolicSimulator.scala:256)
        at uclid.SymbolicSimulator.$anonfun$execute$6$adapted(SymbolicSimulator.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at uclid.SymbolicSimulator.execute(SymbolicSimulator.scala:245)
        at uclid.UclidMain$.execute(UclidMain.scala:486)
        at uclid.UclidMain$.executeCommands(UclidMain.scala:538)
        at uclid.UclidMain$.$anonfun$main$1(UclidMain.scala:179)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at uclid.UclidMain$.main(UclidMain.scala:179)
        at uclid.UclidMain$.main(UclidMain.scala:62)
        at uclid.UclidMain.main(UclidMain.scala)

I'm wondering if the user needs to set some environment variables before running the scripts?

**Comment by saseshia** [comment]
Looks like we do need the uclid sources to be in the repository. So please restore them.

**Comment by polgreen** [comment]
ok, i think this is all fixed now. Will upload the docker image to somewhere (wherever i have enough space)

**Comment by polgreen** [comment]
Added docker image to "onedrive". But feel free to replace with your google drive link.

**Pull request merged**
